<?php

return [
    'CONTACT_SLAG_SERVER_URL'   => env('WEBAPP_URL', 'https://leadip.qkinnovations.com/webapp/') . "contact/detail?contact_id=",
    'PROSPECT_SLAG_SERVER_URL'  => env('WEBAPP_URL', 'https://leadip.qkinnovations.com/webapp/') . "prospect/detail?contact_id=",
    'CLIENT_SLAG_SERVER_URL'    => env('WEBAPP_URL', 'https://leadip.qkinnovations.com/webapp/') . "client/detail?contact_id=",
    'ON_BOARDING_SYNC_WEB_URL'  => env('WEBAPP_URL', 'https://leadip.qkinnovations.com/webapp/') . 'onboarding',
    'SYNC_WEB_URL'              => env('WEBAPP_URL', 'https://leadip.qkinnovations.com/webapp/') . 'contact',
    'SYNC_PROSPECT_URL'         => env('WEBAPP_URL', 'https://leadip.qkinnovations.com/webapp/') . 'prospect',
    'SYNC_CLIENT_URL'           => env('WEBAPP_URL', 'https://leadip.qkinnovations.com/webapp/') . 'client',

    'CREATE_PASSWORD_URL'       => "create-password/",
    "ALLOWED_DOMAINS"           => ['hotmail.com', 'yahoo.com', 'gmail.com', 'icloud.com', 'outlook.com'],

    "super_admin"               => "Super Admin",
    "admin"                     => "Admin",
    "employee"                  => "Employee",

    'DEFAULT_PAGE'              => 1,
    "DEFAULT_PER_PAGE"          => 10,
    "DEFAULT_OFFSET"            => 0,

    "profile_column"            => 11,
    "profile_percentage"        => 33.33,
    "company_column"            => 11,
    "company_percentage"        => 33.33,
    "contact_percentage"        => 33.33,
    "max_percentage"            => 99,

    'company_email_percentage'  => 15,
    'company_name_percentahge'  => 20,
    'company_phone_percentage'  => 15,
    'country_percentage'        => 15,
    'company_city_percentage'   => 5,
    'company_country_percentage'=> 15,
    'category_percentage'       => 15,
    'industry'                  => 5,
    'profile_picture'           => 10,
    'past_year'                 => 2022,
    'total_percentage'          => 100,
    'people_email_percentage'   => 15,
    'first_name_percentage'     => 15,
    'last_name_pecentage'       => 15,
    'people_phone_percentage'   => 15,
    'people_city_percentage'    => 5,
    'people_country_percentage' => 10,
    'point_of_contact'          => 5,
    'people_profile_picture'    => 5,
    'role'                      => 5,
    'linkdin_url'               => 5,

    'company_enrich_email_percentage'    => 20,
    'company_enrich_name_percentage'     => 20,
    'company_enrich_phone_percentage'    => 20,
    'company_enrich_city_percentage'     => 20,
    'company_enrich_country_percentage'  => 20,

    'people_enrich_email_percentage'      => 20,
    'people_enrich_firstname_percentage'  => 10,
    'people_enrich_lastname_percentage'   => 10,
    'people_enrich_phone_percentage'      => 10,
    'people_enrich_city_percentage'       => 10,
    'people_enrich_country_percentage'    => 20,
    'people_enrich_category_percentage'   => 20,

    'APOLLO_API_URL' => env('APOLLO_API_URL','https://api.apollo.io/api/v1/people/bulk_match'),
    'AWS_URL'        => env('AWS_URL','https://leadip-v2-s3-test.s3.ap-south-1.amazonaws.com'),
    'FILE_EXTENTION' => ['png','jpeg','jpg','PDF','CSV','XLS','XLSX','doc','docx','txt'],
];
